version: '3.1'

services:
  local_db:
    image: mysql:8.0
    ports:
        - '3310:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: haggte67qDs
      MYSQL_DATABASE: ladder_db
      MYSQL_USER: ladderuser
      MYSQL_PASSWORD: Fsdmj890
    volumes:
      - ./data/db:/var/lib/mysql

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local