version: '3.1'

services:
  local_db:
    image: mysql:8.0
    ports:
        - '3310:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: haggte67qDs
      MYSQL_DATABASE: ladder_db
      MYSQL_USER: ladderuser
      MYSQL_PASSWORD: Fsdmj890
    volumes:
      - ./data/db:/var/lib/mysql

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'